services:
  - type: web
    name: smarttask-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backend.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
